name: Auto-generate PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'aider'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - uses: mirrajabi/aider-github-action@main
        with:
          issue-number: ${{ github.event.issue.number }}
          branch: ${{ github.event.repository.default_branch }}
          model: sonnet
          anthropic_api_key: ${{ secrets.TSCIRCUIT_BOT_ANTHROPIC_API_KEY }}
