name: Auto-generate PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'aider'
    steps:
      - uses: mirrajabi/aider-github-action@v1.0.1
        with:
          issue-number: ${{ github.event.issue.number }}
          base-branch: ${{ github.event.repository.default_branch }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.TSCIRCUIT_BOT_ANTHROPIC_API_KEY }}
