name: Aider Issue to PR

on:
  issues:
    types: [labeled]

jobs:
  aider-pr:
    if: github.event.label.name == 'aider'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Aider
      uses: mirrajabi/aider-github-action@main
      timeout-minutes: 10 # Prevent accidental high usage
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        model: 'claude-3-sonnet-20240229'
        branch: ${{ github.event.repository.default_branch }}
        aider_args: >-
          --yes
          --message "Apply changes based on issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          ${{ github.event.issue.body }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: aider-changes-issue-${{ github.event.issue.number }}
        title: '[Aider] Changes for issue #${{ github.event.issue.number }}'
        body: |
          This PR was automatically generated by Aider based on issue #${{ github.event.issue.number }}.
          
          Issue Title: ${{ github.event.issue.title }}
          
          Please review the changes and merge if appropriate.
        labels: automated-pr
